# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blogarticles',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogArticles',
        ),
    ]
